### ISSUE TITLE
Astron

### ISSUE THREAD

**Issue by craigy109** [ToontownStrideOfficial/ToontownStride#1]
Whats the astron exe version please

**Comment by Spiderlover** [comment]
yeah, I want to know as well. :)

**Comment by ToontownStrideOfficial** [comment]
There's a specific Panda3D build that's needed to work with this Astron- we'll see if we can bundle it and commit it ASAP :)

**Comment by Spiderlover** [comment]
Thanks for the comment :)

**Comment by craigy109** [comment]
okay thanks if you can do the panda files too would be great thanks

**Comment by Virnios** [comment]
lol

**Comment by craigy109** [comment]
e.s.t on installer?

**Comment by ToontownStrideOfficial** [comment]
Everything is compiled, just setting the correct installation directory

**Comment by craigy109** [comment]
okay

**Comment by ToontownStrideOfficial** [comment]
Here's the build, if one of you could please test to make sure this runs the game that would be good :+1: http://expirebox.com/download/32a79c956508971837e91edb9d91df64.html

**Comment by mgracer48** [comment]
It's Windows

**Comment by mgracer48** [comment]
What about other platforms

**Comment by craigy109** [comment]
does that include astron.exe?

**Comment by ToontownStrideOfficial** [comment]
There isn't a need for astron.exe within the Panda3D build, it has the dependencies needed for astron to run.

**Comment by craigy109** [comment]
okay
ill give it a try

**Comment by craigy109** [comment]
http://prntscr.com/92un07

**Comment by craigy109** [comment]
Astron is not recogniseable

**Comment by ToontownStrideOfficial** [comment]
Thats odd. https://gyazo.com/9fa7b727e8f60c0f30c479bc7dc5aa33
You are running astron-cluster correct? There shouldn't be a need for astrond in this build of Toontown Stride. https://gyazo.com/6ff711c06fa9e63607eccd74dc555f15

**Comment by ToontownStrideOfficial** [comment]
Try updating the source. There's an astrond on my side https://gyazo.com/929e51a8fdb189a83582f687836f41e9

**Comment by craigy109** [comment]
http://prntscr.com/92upvf
its not on the git

**Comment by craigy109** [comment]
the .gitignore stops you uploading it
http://prntscr.com/92uq1r
you need to remove the gitignore to upload it

**Comment by craigy109** [comment]
just need to upload teh astron.exe files now and dll and its all complete then :)

**Comment by Spiderlover** [comment]
yep :)

**Comment by craigy109** [comment]
This is the astron branch been used i checked
https://github.com/Astron/Astron/tree/696a6c43b94995ddc59b5c9ad1024b7652a6786d

either needs exe uploading or when i finish work ill have to compile it

**Comment by ToontownStrideOfficial** [comment]
try the installers provided in the zip, but no guarantee they'll work due to a halt in the upload. We're trying to make it to where we can upload .dll and .exe files

**Comment by craigy109** [comment]
yeah the halt in upload must have corrupted it

**Comment by craigy109** [comment]
astron still doesnt work the .exe hangs

**Comment by ToontownStrideOfficial** [comment]
Have you recently updated the git to where installers are no longer required?

**Comment by craigy109** [comment]
Yes and the astrond.exe does nothing but infinite loading circle

**Comment by ToontownStrideOfficial** [comment]
Try now

**Comment by craigy109** [comment]
yes this fixed it :)
