### ISSUE TITLE
This game is so crap

### ISSUE THREAD

**Issue by TTArchive** [ToontownStrideOfficial/ToontownStride#6]
Come on guys, every boss crashes, I can't even make friends, toon interiors don't work, this game is crap EVEN COG INVASION ONLINE IS BETTER WTF

**Comment by mgracer48** [comment]
Lol

**Comment by mgracer48** [comment]
Says the one who leaked cog invasion

**Comment by LittleNed** [comment]
No need to be rude, The staff are trying, probably better than what you could make TTArchive.

**Comment by LittleNed** [comment]
get deported ttarchive

**Comment by LittleNed** [comment]
Oh and interiors do work f*cker, You haven't downloaded the updated source have you? you prob got the one from april from facebook.

**Comment by TTArchive** [comment]
wtf they don't work look http://i.imgur.com/I1Ypul1.png

**Comment by TTArchive** [comment]
im stuck after walking into one

**Comment by craigy109** [comment]
this is not an issue its called set it up properly on your side or remove the top toons manager same for gardening to work gardening properly you need mongo db these are not something needed in the repo so dont winge about that

**Comment by LittleNed** [comment]
I Fixed the crashes for the bossbattles haven't pushed it yet, its on my git clone on my page :3

**Comment by mgracer48** [comment]
You fixed it?

**Comment by LittleNed** [comment]
also I fixed the crash when getting emotes from the mailbox by myself :D
