### ISSUE TITLE
I found you can change the maxhp of your toon in the astrondb folder

### ISSUE THREAD

**Issue by LittleNed** [ToontownStrideOfficial/ToontownStride#9]
Is their any other way?

**Comment by Spiderlover** [comment]
You can change the Max HP Limit in ToontownGlobals.py

**Comment by ToontownStrideOfficial** [comment]
You can use magic words to modify your HP- should be with ~hp (value) or ~maxhp (value) but not positive.

**Comment by LittleNed** [comment]
Thank you.

**Comment by ToontownStrideOfficial** [comment]
Yep, most of the magic words should be the same as Toontown Infinite's because a lot of the code is stolen from them sadly.

**Comment by Spiderlover** [comment]
you mean reused not stolen, right?

**Comment by ToontownStrideOfficial** [comment]
I mean stolen, there were people planted in Toontown Infinite that stole ideas and code from them during their comeback. The people left in Stride aren't really to be trusted because of this, and the old developers, artists, and even their leader quit.

**Comment by Spiderlover** [comment]
ok, thanks for the info :)
